// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_auth_forgot from "./routes/api/auth/forgot.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_auth_reset from "./routes/api/auth/reset.ts";
import * as $api_children_childId_ from "./routes/api/children/[childId].ts";
import * as $api_children_add from "./routes/api/children/add.ts";
import * as $api_children_cashin from "./routes/api/children/cashin.ts";
import * as $api_children_index from "./routes/api/children/index.ts";
import * as $api_children_points from "./routes/api/children/points.ts";
import * as $api_children_remove from "./routes/api/children/remove.ts";
import * as $api_children_update from "./routes/api/children/update.ts";
import * as $api_tasks_toggle from "./routes/api/tasks/toggle.ts";
import * as $forgot from "./routes/forgot.tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $onboard from "./routes/onboard.tsx";
import * as $reset from "./routes/reset.tsx";
import * as $tracker from "./routes/tracker.tsx";
import * as $welcome from "./routes/welcome.tsx";
import * as $AddChildForm from "./islands/AddChildForm.tsx";
import * as $ChildRow from "./islands/ChildRow.tsx";
import * as $ForgotForm from "./islands/ForgotForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $OnboardForm from "./islands/OnboardForm.tsx";
import * as $ResetForm from "./islands/ResetForm.tsx";
import * as $TrackerView from "./islands/TrackerView.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/forgot.ts": $api_auth_forgot,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/auth/reset.ts": $api_auth_reset,
    "./routes/api/children/[childId].ts": $api_children_childId_,
    "./routes/api/children/add.ts": $api_children_add,
    "./routes/api/children/cashin.ts": $api_children_cashin,
    "./routes/api/children/index.ts": $api_children_index,
    "./routes/api/children/points.ts": $api_children_points,
    "./routes/api/children/remove.ts": $api_children_remove,
    "./routes/api/children/update.ts": $api_children_update,
    "./routes/api/tasks/toggle.ts": $api_tasks_toggle,
    "./routes/forgot.tsx": $forgot,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/onboard.tsx": $onboard,
    "./routes/reset.tsx": $reset,
    "./routes/tracker.tsx": $tracker,
    "./routes/welcome.tsx": $welcome,
  },
  islands: {
    "./islands/AddChildForm.tsx": $AddChildForm,
    "./islands/ChildRow.tsx": $ChildRow,
    "./islands/ForgotForm.tsx": $ForgotForm,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/OnboardForm.tsx": $OnboardForm,
    "./islands/ResetForm.tsx": $ResetForm,
    "./islands/TrackerView.tsx": $TrackerView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
